#!/usr/bin/perl
use strict;
use warnings;
use lib "lib";
use POSIX ":sys_wait_h";
use Sioux;


@ARGV == 1 or die("Il faut un argument après la commande.\n");

if ($ARGV[0] eq "start") {

  die("Le fichier de configuration n'existe pas.\n") unless -e "sioux.conf";
  die("Le serveur est déjà lancé.\n") if -e "lib/.pidpere";

  my $pid = fork();

  if ($pid == 0) {
    do "siouxstart";
  }
  else {
    Sioux::enregistrerPere($pid);
  }
  exit;
}

if ($ARGV[0] eq "stop") {
  do "siouxstop";
  exit;
}

if ($ARGV[0] eq "configure") {
  do "siouxconf";
  exit;
}

die("Cet argument n'existe pas.\n");
