#!/usr/bin/env perl
use strict; # norme d'évaluation des termes plus strict
use warnings; # warnings suplémentaires

my $port;
my $rootdir;
my $index;
my $cgidir;
my $maxclients;

do {
  print "port? : ";
  $port = <STDIN>;
  chomp($port);
} until $port > 1024 && $port <= 65_535;

do {
  print "rootdir? : ";
  $rootdir = <STDIN>;
  chomp($rootdir);
} until -d $rootdir;

do {
  print "index? : ";
  $index = <STDIN>;
  chomp($index);
} until $index =~ /\.html?$/;

do {
  print "cgidir? : ";
  $cgidir = <STDIN>;
  chomp($cgidir);
} until $cgidir ne "" && $cgidir ne $rootdir;

do {
  print "maxclients? : ";
  $maxclients = <STDIN>;
  chomp($maxclients);
} until $maxclients > 0;

open(OUT, ">sioux.conf");
print OUT "port = $port\n";
print OUT "rootdir = $rootdir\n";
print OUT "index = $index\n";
print OUT "cgidir = $cgidir\n";
print OUT "maxclients = $maxclients\n";
close(OUT);
