#!/usr/bin/env perl
use warnings;

$fichpidpere = "lib/.pidpere";
open(FILE,$fichpidpere) or die("erreur fichier $fichpidpere");
while(<FILE>) {
  chomp($_);
  kill(SIGTERM,$_);
}
close(FILE);
unlink $fichpidpere;
