#!/usr/bin/env perl

$fichpidpere = "lib/.pidpere";
$fichpidfils = "lib/.pidfils";
open(FILE,$fichpidpere) or die("erreur fichier $fichpidpere");
while(<FILE>) {
    chomp($_);
    kill(SIGTERM,$_);
}
close(FILE);
unlink $fichpidpere;
unlink $fichpidfils;
